global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:

  # DeployGuard API
  - job_name: "deployguard-api"
    static_configs:
      - targets:
          - "deployguard-api:8000"

  # Pushgateway
  - job_name: "pushgateway"
    static_configs:
      - targets:
          - "pushgateway:9091"